-- =====================================================
-- AJUSTES DE ESQUEMA PARA PROYECTO CLINICA
-- Oracle 19c+
-- =====================================================

-- 1) SECUENCIAS (si ya existen, ignora el error o elimina primero)
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CONSULTORIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BLOQUE_HORARIO START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CITA START WITH 1 INCREMENT BY 1 NOCACHE;

-- 2) TABLA CONSULTORIO
CREATE TABLE CONSULTORIO (
    ID_CONSULTORIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
    UBICACION VARCHAR2(100) NOT NULL
);

-- 3) TABLA BLOQUE_HORARIO con TIMESTAMP
CREATE TABLE BLOQUE_HORARIO (
    ID_BLOQUE NUMBER PRIMARY KEY,
    ID_DOCTOR NUMBER NOT NULL,
    ID_CONSULTORIO NUMBER NOT NULL,
    INICIO_BLOQUE TIMESTAMP NOT NULL,
    FIN_BLOQUE TIMESTAMP NOT NULL,
    ESTADO_BLOQUE VARCHAR2(20) NOT NULL,
    CONSTRAINT FK_BLOQUE_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR),
    CONSTRAINT FK_BLOQUE_CONSULTORIO FOREIGN KEY (ID_CONSULTORIO) REFERENCES CONSULTORIO(ID_CONSULTORIO),
    CONSTRAINT CHK_BLOQUE_ESTADO CHECK (ESTADO_BLOQUE IN ('RESERVADO', 'CANCELADO')),
    CONSTRAINT CHK_BLOQUE_FECHAS CHECK (INICIO_BLOQUE < FIN_BLOQUE)
);

-- 4) AJUSTES A CITA
ALTER TABLE CITA DROP COLUMN ID_DOCTOR;
ALTER TABLE CITA MODIFY (ID_PACIENTE NULL);
ALTER TABLE CITA ADD CONSTRAINT FK_CITA_BLOQUE FOREIGN KEY (ID_BLOQUE) REFERENCES BLOQUE_HORARIO(ID_BLOQUE);
ALTER TABLE CITA ADD CONSTRAINT FK_CITA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE);
ALTER TABLE CITA ADD CONSTRAINT CHK_CITA_ESTADO CHECK (ESTADO_CITA IN ('DISPONIBLE','RESERVADA','CANCELADA','ATENDIDA','AUSENTE'));
ALTER TABLE CITA ADD CONSTRAINT CHK_CITA_FECHAS CHECK (INICIO_CITA < FIN_CITA);

-- 5) ÍNDICES ÚTILES
CREATE UNIQUE INDEX UK_USUARIO_USERNAME ON USUARIO(USERNAME);
CREATE UNIQUE INDEX UK_USUARIO_CORREO ON USUARIO(CORREO);
CREATE INDEX IDX_BLOQUE_RANGO ON BLOQUE_HORARIO(INICIO_BLOQUE, FIN_BLOQUE);
CREATE INDEX IDX_CITA_RANGO ON CITA(ID_BLOQUE, INICIO_CITA, FIN_CITA);
CREATE INDEX IDX_CITA_ESTADO ON CITA(ESTADO_CITA);

-- 6) CONSULTORIO PRINCIPAL
INSERT INTO CONSULTORIO (ID_CONSULTORIO, NOMBRE, UBICACION)
VALUES (1, 'Consultorio Principal', 'Clínica - Sala 1');

COMMIT;
