-- =====================================================
-- TRIGGERS PARA AUTOGENERAR IDS CON SEQUENCIAS
-- =====================================================

CREATE OR REPLACE TRIGGER TRG_USUARIO_BI
BEFORE INSERT ON USUARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
        SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CONSULTORIO_BI
BEFORE INSERT ON CONSULTORIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_CONSULTORIO IS NULL THEN
        SELECT SEQ_CONSULTORIO.NEXTVAL INTO :NEW.ID_CONSULTORIO FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BLOQUE_BI
BEFORE INSERT ON BLOQUE_HORARIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_BLOQUE IS NULL THEN
        SELECT SEQ_BLOQUE_HORARIO.NEXTVAL INTO :NEW.ID_BLOQUE FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CITA_BI
BEFORE INSERT ON CITA
FOR EACH ROW
BEGIN
    IF :NEW.ID_CITA IS NULL THEN
        SELECT SEQ_CITA.NEXTVAL INTO :NEW.ID_CITA FROM DUAL;
    END IF;
END;
/
